name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Update vcpkg repository
      working-directory: vcpkg
      run: |
        git fetch --all --prune
        git checkout master
        git pull

    - name: Update vcpkg ports
      run: |
        .\vcpkg\vcpkg.exe update

    - name: Install PCL
      run: |
        .\vcpkg\vcpkg.exe install pcl:x64-windows

    - name: Clean up vcpkg buildtrees, downloads, and packages
      run: |
        Remove-Item -Path .\vcpkg\buildtrees\* -Recurse -Force
        Remove-Item -Path .\vcpkg\downloads\* -Recurse -Force
        Remove-Item -Path .\vcpkg\packages\* -Recurse -Force

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
